Repository binbashar/le-ref-architecture-doc, pull requests merged in 2021-08, with the labels that each got.

#80 LEWW-71 | upgrade mkdocs ver + work with us section + tf vault repo added + adding tgw, nfw and cicd diagrams + adding leverage cli section
  Makefile
  docs/assets/images/diagrams/aws-acm.png
  docs/assets/images/diagrams/aws-k8s-eks-ci-cd-argocd.png
  docs/assets/images/diagrams/aws-k8s-eks-demoapps-components.png
  docs/assets/images/diagrams/aws-tgw-nfw.png
  docs/assets/images/diagrams/aws-tgw.png
  docs/assets/images/diagrams/cert-manager.svg
  docs/assets/images/screenshots/vault-ui-auth-github.png
  docs/how-it-works/ci-cd/k8s-argocd.md
  docs/how-it-works/index.md
  docs/how-it-works/leverage-cli/index.md
  docs/how-it-works/network/tgw-topology.md
  docs/how-it-works/network/vpc-traffic-out.md
  docs/how-it-works/organization/accounts.md
  docs/how-it-works/organization/organization.md
  docs/how-it-works/reliability/backups.md
  docs/how-it-works/security/certificates.md
  docs/how-it-works/why.md
  docs/user-guide/base-configuration/overview.md
  docs/user-guide/base-configuration/repo-le-tf-infra-aws.md
  docs/user-guide/base-configuration/repo-le-tf-vault.md
  docs/user-guide/base-workflow/repo-le-dev-makefiles.md
  docs/user-guide/base-workflow/repo-le-tf-infra-aws-tf-state.md
  docs/user-guide/base-workflow/repo-le-tf-infra.md
  docs/user-guide/identities/credentials-vault.md
  docs/user-guide/identities/credentials.md
  docs/user-guide/index.md
  docs/user-guide/network/dns.md
  docs/user-guide/organization/organization-init.md
  docs/welcome.md
  docs/work-with-us/faqs.md
  docs/work-with-us/index.md
  material/overrides/home-es.html
  material/overrides/home.html
  material/overrides/main.html
  material/overrides/subscription-plans.html
  mkdocs.yml
Labels: documentation, feature, patch

#81 LEWW-71 | several updates and fixes - work with us and subscription
  docs/how-it-works/costs/costs.md
  docs/work-with-us/faqs.md
  docs/work-with-us/index.md
  material/overrides/subscription-plans.html
  mkdocs.yml
Labels: bug, patch

#82 LEWW-71 | updating landing header + work with us sintaxt fixes
  docs/work-with-us/faqs.md
  docs/work-with-us/index.md
  material/overrides/home.html
Labels: bug, patch

#83 First Steps guide & Leverage CLI documentation
  docs/examples/PREREQUISITES.md
  docs/examples/http-svc.yaml
  docs/examples/index.md
  docs/examples/k8s-kops.md
  docs/examples/organization.md
  docs/first-steps/index.md
  docs/how-it-works/code-library/code-library-specs.md
  docs/how-it-works/compute/k8s-eks.md
  docs/how-it-works/costs/costs.md
  docs/how-it-works/database/database.md
  docs/how-it-works/identities/identities.md
  docs/how-it-works/index.md
  docs/how-it-works/leverage-cli/index.md
  docs/how-it-works/network/dns.md
  docs/how-it-works/network/tgw-topology.md
  docs/how-it-works/network/vpc-addressing.md
  docs/how-it-works/network/vpc-topology.md
  docs/how-it-works/network/vpc-traffic-out.md
  docs/how-it-works/organization/organization.md
  docs/how-it-works/reliability/high-availability.md
  docs/how-it-works/security/certificates.md
  docs/how-it-works/security/iam-access-analyzer.md
  docs/how-it-works/security/services.md
  docs/how-it-works/security/vpn.md
  docs/user-guide/base-configuration/overview.md
  docs/user-guide/base-configuration/repo-le-ansible-infra.md
  docs/user-guide/base-configuration/repo-le-tf-infra-aws.md
  docs/user-guide/base-workflow/leverage-cli.md
  docs/user-guide/base-workflow/leverage-cli/install-leverage-cli.md
  docs/user-guide/base-workflow/leverage-cli/reference/basic-features.md
  docs/user-guide/base-workflow/leverage-cli/reference/credentials.md
  docs/user-guide/base-workflow/leverage-cli/reference/project.md
  docs/user-guide/base-workflow/leverage-cli/reference/run.md
  docs/user-guide/base-workflow/leverage-cli/reference/terraform.md
  docs/user-guide/base-workflow/leverage-cli/tasks.md
  docs/user-guide/base-workflow/repo-le-tf-infra-aws-tf-state.md
  docs/user-guide/base-workflow/repo-le-tf-infra.md
  docs/user-guide/compute/k8s-kops.md
  docs/user-guide/identities/credentials-vault.md
  docs/user-guide/identities/credentials.md
  docs/user-guide/identities/gpg.md
  docs/user-guide/network/dns.md
  docs/user-guide/organization/organization-init.md
  docs/user-guide/organization/organization-legacy-accounts.md
  docs/work-with-us/careers.md
  docs/work-with-us/faqs.md
  docs/work-with-us/roadmap/leverage-cli/overview.md
  mkdocs.yml
Labels: feature, patch

#85 Feature/team updated and updating core components to follow its exact names
  .github/ISSUE_TEMPLATE/config.yml
  docs/assets/images/collaborators/matias.rodriguez.png
  docs/assets/images/diagrams/infra-as-code-library-reuse.png
  docs/assets/images/diagrams/infra-as-code-library-specs.png
  docs/assets/images/diagrams/infra-as-code-library-workflow.png
  docs/assets/images/team/matias.rodriguez.bwc.png
  docs/first-steps/index.md
  docs/how-it-works/index.md
  docs/how-it-works/infra-as-code-library/infra-as-code-library-forks.md
  docs/how-it-works/infra-as-code-library/infra-as-code-library-specs.md
  docs/how-it-works/infra-as-code-library/infra-as-code-library.md
  docs/how-it-works/infra-as-code-library/modules-library-per-tech.md
  docs/user-guide/base-configuration/repo-le-ansible-infra.md
  docs/user-guide/base-workflow/repo-le-tf-infra-aws-tf-state.md
  docs/welcome.md
  docs/work-with-us/careers.md
  material/overrides/home-es.html
  material/overrides/home.html
  material/overrides/work-with-us/team.html
  mkdocs.yml
Labels: documentation, patch
