Repository binbashar/le-ref-architecture-doc, pull requests merged in 2021-09, with the labels that each got.

#86 Split first steps guide into smaller sections
  docs/assets/stylesheets/extra.css
  docs/first-steps/aws-account-setup.md
  docs/first-steps/index.md
  docs/first-steps/introduction.md
  docs/first-steps/leverage-project-setup.md
  docs/first-steps/local-setup.md
  docs/first-steps/management-account.md
  docs/first-steps/post-deployment.md
  docs/first-steps/security-and-shared-accounts.md
  mkdocs.yml
Labels: enhancement, patch

#90 Feature/team memeber
  docs/assets/images/collaborators/alejandro.parise.png
  docs/assets/images/team/alejandro.parise.bwc.png
  docs/how-it-works/infra-as-code-library/infra-as-code-library-specs.md
  material/overrides/home-es.html
  material/overrides/home.html
  material/overrides/work-with-us/subscription-plans.html
  material/overrides/work-with-us/team.html
Labels: bug, patch

#95 Fix/ small format fix + testing automated deployment pipeline
  docs/how-it-works/features/reliability/backups.md
Labels: minor, fix

#96 Fix/first steps intro fig link + circleci deployment command
  .circleci/config.yml
  docs/first-steps/introduction.md
  material/overrides/work-with-us/leverage-vs-competition.html
Labels: minor, fix
