Repository binbashar/le-ref-architecture-doc, pull requests merged in 2022-01, with the labels that each got.

#106 Feature/add feature overview section + diagram updates
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  Makefile
  docs/assets/images/diagrams/aws-sso.png
  docs/assets/images/diagrams/editable/leverage-aws-landing-zone-base.xml
  docs/assets/images/diagrams/editable/leverage-landing-zone.xml
  docs/assets/images/diagrams/editable/ref-architecture-aws.xml
  docs/assets/images/diagrams/editable/ref-architecture-eks-components.xml
  docs/assets/images/diagrams/editable/ref-architecture-eks.xml
  docs/assets/images/diagrams/leverage-landing-zone.png
  docs/assets/images/diagrams/ref-architecture-aws-landing-zone.png
  docs/assets/images/diagrams/ref-architecture-aws.png
  docs/assets/images/diagrams/ref-architecture-eks-components.png
  docs/assets/images/diagrams/ref-architecture-eks.png
  docs/first-steps/introduction.md
  docs/first-steps/post-deployment.md
  docs/how-it-works/considerations.md
  docs/how-it-works/design/considerations.md
  docs/how-it-works/design/general-concepts/why-leverage.md
  docs/how-it-works/design/general-concepts/why-tech-stack.md
  docs/how-it-works/design/index.md
  docs/how-it-works/design/reference-architecture-aws.md
  docs/how-it-works/design/reference-architecture-eks.md
  docs/how-it-works/features/compute/tools.md
  docs/how-it-works/features/features-overview.md
  docs/how-it-works/features/sso/sso.md
  docs/how-it-works/index.md
  docs/user-guide/features/features-overview.md
  docs/user-guide/features/sso/sso.md
  docs/user-guide/features/tools/tools.md
  docs/welcome.md
  docs/work-with-us/careers.md
  docs/work-with-us/contact.md
  docs/work-with-us/faqs.md
  mkdocs.yml
Labels: feature, patch

#107 Feature/prd isolation driagrams
  docs/assets/diagrams/editable/TGW Isolation.drawio.xml
  docs/assets/diagrams/editable/leverage-aws-network-tgw- TGW Multi region.drawio.xml
  docs/assets/diagrams/editable/leverage-aws-network-tgw-TGW + NFW Multi region.drawio.xml
Labels: documentation, patch

#108 Feature/ Google Anlytics versions G4 + Navigation tree and sections updated
  docs/first-steps/post-deployment.md
  docs/how-it-works/leverage-cli/index.md
  docs/how-it-works/ref-architecture/considerations.md
  docs/how-it-works/ref-architecture/general-concepts/why-leverage.md
  docs/how-it-works/ref-architecture/general-concepts/why-tech-stack.md
  docs/how-it-works/ref-architecture/index.md
  docs/how-it-works/ref-architecture/ref-architecture-aws.md
  docs/how-it-works/ref-architecture/ref-architecture-eks.md
  docs/user-guide/base-configuration/overview.md
  docs/user-guide/features/network/dns.md
  docs/user-guide/index.md
  docs/user-guide/leverage-cli/install-leverage-cli.md
  docs/user-guide/leverage-cli/reference/basic-features.md
  docs/user-guide/leverage-cli/reference/credentials.md
  docs/user-guide/leverage-cli/reference/project.md
  docs/user-guide/leverage-cli/reference/run.md
  docs/user-guide/leverage-cli/reference/terraform.md
  docs/user-guide/leverage-cli/tasks.md
  docs/user-guide/ref-architecture-ansible/configs.md
  docs/user-guide/ref-architecture-ansible/workflow.md
  docs/user-guide/ref-architecture-aws/configs.md
  docs/user-guide/ref-architecture-aws/credentials.md
  docs/user-guide/ref-architecture-aws/dir-structure.md
  docs/user-guide/ref-architecture-aws/tf-state-setup.md
  docs/user-guide/ref-architecture-aws/tf-state-workflow.md
  docs/user-guide/ref-architecture-aws/workflow.md
  docs/user-guide/ref-architecture-vault/configs.md
  docs/user-guide/ref-architecture-vault/dir-structure.md
  docs/user-guide/ref-architecture-vault/tf-state-workflow.md
  docs/user-guide/ref-architecture-vault/workflow.md
  docs/welcome.md
  docs/work-with-us/archived/contact.md.back
  docs/work-with-us/archived/subscription-plans.md.back
  docs/work-with-us/archived/team.md.back
  docs/work-with-us/archived/testimonials.md.back
  docs/work-with-us/careers.md
  docs/work-with-us/faqs.md
  docs/work-with-us/updates/product-updates-12-2021.md
  mkdocs.yml
Labels: documentation, patch

#109 Updating ENV var for Google Analytics G4 version
  .circleci/config.yml
Labels: feature, patch

#110 Update TGW isolation diagrams
  docs/assets/diagrams/editable/TGW Isolation.drawio.xml
Labels: documentation, patch

#111 fix/ updating to latest mkdocs version + tab feature fix
  Makefile
  mkdocs.yml
Labels: patch, fix
