Repository binbashar/le-ref-architecture-doc, pull requests merged in 2023-04, with the labels that each got.

#165 Fix the height of the logo as it was covering the 'First steps' link …
  material/overrides/main-styles.html
Labels: patch, fix

#156 ISSUE-173 added documentation on ssh-agent usage
  docs/first-steps/post-deployment.md
  docs/user-guide/leverage-cli/reference/private-repos.md
  docs/user-guide/leverage-cli/shell.md
  mkdocs.yml
Labels: enhancement, patch

#169 Enhancement | Document verbose flag
  .circleci/config.yml
  docs/assets/stylesheets/extra.css
  docs/user-guide/leverage-cli/reference/basic-features.md
  mkdocs.yml
Labels: enhancement, patch

#168 Doc | first-steps/post-deployment: add procedure to add new aws accounts.
  docs/first-steps/post-deployment.md
Labels: documentation

#172 ISSUE-158 | add new aws account
  docs/first-steps/add-aws-accounts.md
  docs/first-steps/post-deployment.md
  mkdocs.yml
Labels: documentation, patch
