Repository binbashar/le-ref-architecture-doc, pull requests merged in 2023-05, with the labels that each got.

#177 BBL-105 | Fix: increase size footer social media icons
  docs/assets/stylesheets/extra.css
  material/overrides/home-es.html
  material/overrides/home.html
Labels: patch, fix

#179 BBL-105 | Fix: improve seo for mobile version
  docs/assets/stylesheets/extra.css
  docs/user-guide/ref-architecture-eks/cluster-upgrade.md
  docs/user-guide/ref-architecture-eks/overview.md
  material/overrides/home-es.html
  material/overrides/home.html
Labels: documentation

#180 Fix | broken links at references.md
  docs/user-guide/ref-architecture-aws/references.md
Labels: patch, fix

#181 LEWW-101 | update work-with-us with new images
  docs/assets/images/diagrams/ref-architecture-collab-methodology.png
  docs/assets/images/diagrams/ref-architecture-support.png
Labels: documentation, patch
