Repository binbashar/le-ref-architecture-doc, pull requests merged in 2023-03, with the labels that each got.

#159 Doc | minor sintaxt fix at why-leverage.md
  docs/how-it-works/ref-architecture/general-concepts/why-leverage.md
Labels: documentation, patch

#157 new langing page
  docs/assets/images/diagrams/AWS-ORGANIZATION.png
  docs/assets/images/diagrams/diagrama-organization-binbash.png
  docs/assets/images/icons/check-ok.svg
  docs/assets/images/illustrations/Ilustracion-Binbash.png
  docs/assets/images/illustrations/mock-mac-book-16.png
  docs/assets/images/illustrations/why-leverage.svg
  docs/assets/images/logos/binbash-landing-header.svg
  docs/assets/images/logos/binbash-nav-icon.svg
  docs/assets/images/logos/leverage-title-logo.svg
  docs/assets/images/logos/logo-binbash.png
  docs/assets/images/logos/socialmedia/github.svg
  docs/assets/images/logos/socialmedia/instagram.svg
  docs/assets/images/logos/socialmedia/linkedIn.svg
  docs/assets/images/logos/socialmedia/medium.svg
  docs/assets/images/logos/socialmedia/slack.svg
  docs/assets/images/logos/socialmedia/twitter.svg
  docs/assets/images/logos/stack-tecnologico-2.svg
  docs/assets/images/logos/stack-tecnology.svg
  docs/assets/stylesheets/extra.css
  docs/assets/stylesheets/typography/Telegraf-Regular.otf
  docs/assets/stylesheets/typography/Telegraf-UltraBold.otf
  docs/es.md
  docs/index.md
  material/overrides/home-es.html
  material/overrides/home.html
  material/overrides/main-styles.html
  mkdocs.yml
Labels: documentation, enhancement

#161 Doc | updating leverage ref arch diagram + spanish copy
  Makefile
  docs/assets/images/illustrations/banner-alt.png
  docs/assets/images/illustrations/banner.png
  material/overrides/home-es.html
  material/overrides/home.html
  material/overrides/main-styles.html
  material/overrides/work-with-us/leverage-vs-competition.html
Labels: documentation, patch

#162 Enhancement | minor landing text and color adjustments
  material/overrides/home-es.html
  material/overrides/home.html
  material/overrides/main.html
Labels: enhancement, patch

#154 Kubectl command documentation
  docs/user-guide/leverage-cli/install-leverage-cli.md
  docs/user-guide/leverage-cli/reference/basic-features.md
  docs/user-guide/leverage-cli/reference/kubectl.md
  mkdocs.yml
Labels: documentation, minor
