Repository binbashar/le-ref-architecture-doc, pull requests merged in 2024-06, with the labels that each got.

#219 Docs | Update EKS cluster upgrade docs
  docs/user-guide/ref-architecture-eks/cluster-upgrade.md
Labels: documentation, minor

#220 Update SSO config page with additional steps regarding MFA and sessio…
  docs/user-guide/ref-architecture-aws/features/sso/configuration.md
Labels: documentation, enhancement

#213 Feature/k8s playbook
  docs/assets/diagrams/argocd-externalcluster-basic.png
  docs/assets/diagrams/argocd-externalcluster-bigpicture.png
  docs/assets/diagrams/argocd-externalcluster-token.png
  docs/user-guide/cookbooks/VPC-subnet-calculator.md
  docs/user-guide/cookbooks/VPC-with-no-LandingZone.md
  docs/user-guide/cookbooks/argocd-external-cluster.md
  docs/user-guide/cookbooks/enable-nat-gateway.md
  docs/user-guide/cookbooks/index.md
  docs/user-guide/cookbooks/k8s.md
  docs/user-guide/cookbooks/schedule-start-stop-ec2.md
  docs/user-guide/cookbooks/sops-kms.md
  docs/user-guide/playbooks/index.md
  mkdocs.yml
Labels: documentation, enhancement

#217 FEATURE/ added VPN document
  docs/user-guide/cookbooks/VPN-server.md
  docs/user-guide/cookbooks/index.md
  mkdocs.yml
Labels: feature, patch
