Repository binbashar/le-ref-architecture-doc, pull requests merged in 2024-02, with the labels that each got.

#207 Create index page for credentials under AWS and EKS reference architectures
  docs/user-guide/ref-architecture-aws/configuration.md
  docs/user-guide/ref-architecture-aws/credentials.md
  docs/user-guide/ref-architecture-eks/credentials.md
  mkdocs.yml
Labels: documentation, patch

#205 [BB-233] shell section + terraform updates
  docs/user-guide/leverage-cli/basic-features.md
  docs/user-guide/leverage-cli/reference/shell.md
  docs/user-guide/leverage-cli/reference/terraform.md
  mkdocs.yml
Labels: feature, patch

#208 [BB-233] No need to run `configure sso` more than once now
  docs/user-guide/ref-architecture-aws/features/sso/configuration.md
Labels: patch, fix

#210 ENHANCEMENT | improved the doc on what is the correct name for management acc
  docs/try-leverage/aws-account-setup.md
Labels: enhancement, patch

#211 Fix credentials links
  docs/user-guide/ref-architecture-aws/credentials.md
  docs/user-guide/ref-architecture-eks/credentials.md
Labels: fix
