Repository binbashar/le-ref-architecture-doc, pull requests merged in 2024-04, with the labels that each got.

#212 Enhancement | Add components documentation
  docs/assets/diagrams/editable/leverage-aws-eks-components-ref-arch.drawio
  docs/assets/diagrams/editable/leverage-aws-eks-ref-arch.drawio
  docs/assets/images/diagrams/ref-architecture-eks-components.png
  docs/user-guide/ref-architecture-eks/components.md
Labels: documentation, enhancement

#215 Docs | Update EKS cluster upgrade docs
  docs/user-guide/ref-architecture-eks/cluster-upgrade.md
Labels: documentation, minor

#214 Feature | AWS SSM start-session integration with leverage + SSO
  docs/user-guide/ref-architecture-aws/features/ssm/ssm.md
  mkdocs.yml
Labels: documentation, patch
